#!/usr/bin/env bash
#
# This is a STARTING POINT, not an answer. Copy the whole EXAMPLE folder to
# submissions/<your-github-username>/ and work in your copy.
#
# Do not edit this file. It is ignored when marking.

set -euo pipefail

dir="${1:?usage: report.sh <directory>}"

echo "FILES: $(find "$dir" -type f | wc -l | tr -d ' ')"
echo "DIRS: $(find "$dir" -mindepth 1 -type d | wc -l | tr -d ' ')"

echo "LARGEST:"
find "$dir" -type f -exec ls -ln {} + 2>/dev/null | \
  awk '{print $5, $NF}' | \
  sort -nr -k1,1 | \
  head -n 3 || true
# three lines, each "<bytes> <path>", biggest first

echo "EXECUTABLE:"
find "$TARGET_DIR" -type f -perm -100 | sort || true
# one path per line, alphabetical

echo "EXTENSIONS:"
# five lines, each "<count> <extension>", commonest first
