#!/usr/bin/env bash
#
# This is a STARTING POINT, not an answer. Copy the whole EXAMPLE folder to
# submissions/<your-github-username>/ and work in your copy.
#
# Do not edit this file. It is ignored when marking.

set -euo pipefail

dir="${1:?usage: report.sh <directory>}"

cd "$dir"

files_count=$(find . -type f | wc -l | tr -d ' ')
dirs_count=$(find . -mindepth 1 -type d | wc -l | tr -d ' ')

echo "FILES: $files_count"
echo "DIRS: $dirs_count"

echo "LARGEST:"
find . -type f -exec wc -c {} + 2>/dev/null \
  | grep -v ' total$' \
  | awk '{
      path=$2;
      for(i=3; i<=NF; i++) path=path" "$i;
      sub(/^\.\//, "", path);
      print $1, path
    }' \
  | sort -nr -k1,1 \
  | head -n 3
# three lines, each "<bytes> <path>", biggest first

echo "EXECUTABLE:"
find . -type f -exec test -x {} \; -print \
  | sed 's|^\./||' \
  | sort
# one path per line, alphabetical

echo "EXTENSIONS:"
find . -type f \
  | grep -E '\.[^/.]+$' \
  | sed -E 's/.*\.//' \
  | sort \
  | uniq -c \
  | sort -nr -k1,1 \
  | head -n 5 \
  | awk '{print $1 " ." $2}'
# five lines, each "<count> <extension>", commonest first