#!/usr/bin/env bash
#
# This is a STARTING POINT, not an answer. Copy the whole EXAMPLE folder to
# submissions/<your-github-username>/ and work in your copy.
#
# Do not edit this file. It is ignored when marking.

set -euo pipefail

dir="${1:?usage: report.sh <directory>}"

files=$(find "$dir" -type f | wc -l | tr -d ' ')
dirs=$(find "$dir" -type d | wc -l | tr -d ' ')
dirs=$((dirs - 1))

echo "FILES: $files"
echo "DIRS: $dirs"

echo "LARGEST:"
# three lines, each "<bytes> <path>", biggest first
find "$dir" -type f -print0 |
while IFS= read -r -d '' file; do
    size=$(wc -c < "$file" | tr -d ' ')
    path="${file#"$dir"/}"
    printf '%s %s\n' "$size" "$path"
done |
sort -nr |
sed -n '1,3p'


echo "EXECUTABLE:"
# one path per line, alphabetical
find "$dir" -type f -perm -u+x -print |
while IFS= read -r file; do
    path="${file#"$dir"/}"
    printf '%s\n' "$path"
done |
sort


echo "EXTENSIONS:"
# five lines, each "<count> <extension>", commonest first
find "$dir" -type f -print |
while IFS= read -r file; do
    name="${file##*/}"
    case "$name" in
        *.*)
            ext="${name##*.}"
            printf '%s\n' "$ext"
            ;;
    esac
done |
sort |
uniq -c |
sort -k1,1nr -k2,2 |
sed -n '1,5p' |
awk '{print $1, "." $2}'
