#!/usr/bin/env bash
#
# This is a STARTING POINT, not an answer. Copy the whole EXAMPLE folder to
# submissions/<your-github-username>/ and work in your copy.
#
# Do not edit this file. It is ignored when marking.

set -euo pipefail

dir="${1:?usage: report.sh <directory>}"

files=$(find "$dir" -type f | wc -l)
dirs=$(find "$dir" -mindepth 1 -type d | wc -l)

echo "FILES: $files"
echo "DIRS: $dirs"

echo "LARGEST:"
# three lines, each "<bytes> <path>", biggest first
(
    cd "$dir"
    if stat -c '%s %n' . >/dev/null 2>&1; then
        find . -type f -exec stat -c '%s %n' {} \;
    else
        find . -type f -exec stat -f '%z %N' {} \;
    fi
) |
    sort -nr |
    head -3
    
echo "EXECUTABLE:"
# one path per line, alphabetical
find "$dir" -type f -perm -u+x |
    sort |
    sed "s|^$dir/||"

echo "EXTENSIONS:"
# five lines, each "<count> <extension>", commonest first
find "$dir" -type f |
while IFS= read -r file; do
    name="${file##*/}"
    if [[ "$name" == *.* && "$name" != .* && "$name" != *. ]]; then
        ext="${name##*.}"
        echo "$ext"
    fi
done |
sort |
uniq -c |
sort -k1,1nr -k2,2 |
head -5 |
awk '{print $1, "." $2}'