#!/usr/bin/env bash
#
# This is a STARTING POINT, not an answer. Copy the whole EXAMPLE folder to
# submissions/<your-github-username>/ and work in your copy.
#
# Do not edit this file. It is ignored when marking.

set -euo pipefail

dir="${1:?usage: report.sh <directory>}"

echo "FILES: $(find "$dir" -type f | wc -l)"
echo "DIRS: $(find "$dir" -mindepth 1 -type d | wc -l)"

echo "LARGEST:"
find "$dir" -type f -printf '%s %P\n' \
    | sort -k1,1nr -k2,2 \
    | head -n 3

echo "EXECUTABLE:"
find "$dir" -type f -perm -100 -printf '%P\n' \
    | sort

echo "EXTENSIONS:"
find "$dir" -type f -printf '%f\n' \
    | awk '
        match($0, /\.[^.]+$/) && RSTART > 1 {
            ext = substr($0, RSTART)
            count[ext]++
        }

        END {
            for (ext in count) {
                print count[ext], ext
            }
        }
    ' \
    | sort -k1,1nr -k2,2 \
    | head -n 5
