#!/usr/bin/env bash
#
# This is a STARTING POINT, not an answer. Copy the whole EXAMPLE folder to
# submissions/<your-github-username>/ and work in your copy.
#
# Do not edit this file. It is ignored when marking.

set -euo pipefail

dir="${1:?usage: report.sh <directory>}"

echo "FILES: $(find "$dir" -mindepth 1 -type f | wc -l)"
echo "DIRS: $(find "$dir" -mindepth 1 -type d | wc -l)"

echo "LARGEST: "
find "$dir" -type f -printf "\n%s %p" | sort -k1,1 -r | head -n 3 | sed "s|$dir/||"
# three lines, each "<bytes> <path>", biggest first

echo "EXECUTABLE:"
find "$dir" -type f -perm -u=x |
    sed "s|$dir/||" |
    sort

echo "EXTENSIONS:"
find "$dir" -type f |
    sed 's|.*/||' |
    grep '\.' |
    sed 's/^.*\.//' |
    sort |
    uniq -c |
    sort -k1,1nr -k2,2 |
    head -5 |
    awk '{print $1, "." $2}'
# five lines, each "<count> <extension>", commonest first

#find /tmp/tree -type f -printf '%M %p\n'