#!/usr/bin/env bash
#
# This is a STARTING POINT, not an answer. Copy the whole EXAMPLE folder to
# submissions/<your-github-username>/ and work in your copy.
#
# Do not edit this file. It is ignored when marking.

set -euo pipefail

dir="${1:?usage: report.sh <directory>}"

cd "$dir"

echo "FILES: $(find . -type f | wc -l)"
echo "DIRS: $(find . -mindepth 1 -type d | wc -l | tr -d ' ')"

echo "LARGEST:"
find . -type f | while read f; do echo $(wc -c < "$f") "$f"; done | sort -nr | head -3
 
echo "EXECUTABLE:"
find . -type f -perm -u+x | sort
 
echo "EXTENSIONS:"
find . -type f -name "*.*" | sed 's/.*\./\./' | sort | uniq -c | sort -nr | head -5 | awk '{print $1, $2}'