#!/usr/bin/env bash
#
# This is a STARTING POINT, not an answer. Copy the whole EXAMPLE folder to
# submissions/<your-github-username>/ and work in your copy.
#
# Do not edit this file. It is ignored when marking.

set -euo pipefail

dir="${1:?usage: report.sh <directory>}"

echo "FILES: $(find "$dir" -type f | wc -l)"
echo "DIRS: $(find "$dir" -mindepth 1 -type d | wc -l)"

echo "LARGEST:"
echo  "$(find "$dir" -type f -printf "%s %P\n" | sort -nr | head -3)"
# three lines, each "<bytes> <path>", biggest first

echo "EXECUTABLE:"
echo "$(find "$dir" -type f -executable -printf "%P\n" | sort)"
# one path per line, alphabetical

echo "EXTENSIONS:"
echo "$(find "$dir" -type f | awk -F. 'NF>1 {print "."$NF}' | sort | uniq -c | sort -nr | head -5)"
# five lines, each "<count> <extension>", commonest first
